import Head from "next/head";
import styles from "./Home.module.scss";
import { NextPage } from "next";

const Home: NextPage = () => {
  console.log(styles);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>X</main>
    </>
  );
};

export default Home;
